### ISSUE TITLE
Include explanation of "fight" mechanics.

### ISSUE THREAD

**Issue by plenge** [BattleBlox/frontend#1]
**Feature Request:** 

Simple and fun, I love the game :) Great job!

I find it a bit confusing sometimes when a tile beats another.
Maybe a quick explanation in the Readme or the slider, describing the mechanics as to how it works when calculating who beats who. Sometimes a lower number beats a higher. 

Is it the bonuspoints that have an influence? or is it random?

**Comment by tommcclean** [comment]
Hey @plenge thanks for the feature request; I am working on a tutorial mechanic I think will make this much clearer.

To answer your questions in the meantime and I will also add these to a readme too.

- Every battle still has an element of chance - so a 10 tile versus a 9 tile is not guaranteed a win; every point is contested, this favours the attacker 70 percent of the time; so its generally better to attack than be attacked :)

**Bonus Points**
- Yeah Bonus points do have a strong influence - there are two types, Expansion and Capital Bonuses.
- When you roll at the end of your turn, you get between a 1 or a 6, your bonus is added to the dice roll
- You get an extra bonus point for every 4 tiles under your control
- You get 2 extra points for every Capital tile (A tile with 10 or higher points)
- So you can choose based on the map layout whether a quick expansion is best, or building stronger tiles instead to begin with.
- In tighter maps; the computer player tends to go for Capital tiles quite early on, before expanding quickly for example. But in a wide open map; they are likely to expand fast and come for you

**Comment by plenge** [comment]
Hi @tommcclean 

Ah, then I was on the right path.
Very familiar to board games like Risk, I like it!

But yeah, either a tutorial or an actual animation showing the fight.
My team and I might fork at some point to add a fight animation showing each point contested, for extra suspense, when we get some time off.

Thanks for the explanation, we have had great fun with it here at the office :) 
We'll be following the process.

Take care!
